# -*- coding: utf-8 -*-
"""AIML ASSIGNMENT 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dlzlZqgNWjfM8bjiauOyawr9XjKY24Ru

Part 1 – Implement Basic Data Structures using Numpy, Pandas
1. Lists
2. Arrays
3. Identify their type using type()
4. Perform mathematical operations on these datasets created - multiplication, division,
poweroff
5. Combine text with Numpy fuction to generate a textual output - ”Addition of Two:
array1 +array 2
6. Implement np.sin(), log(), log2(), np.exp())
"""

import numpy as np
l1=[1,2,3,4]
array1=np.array(l1)
print(array1)

type(l1)

type(array1)

l2=[5,6,7,8]
array2=np.array(l2)
print(array2)

print("multiplication of Two = ",array1*array2)
print("Divison of Two = ",array2/array1)
print("Power Off Two = ",array2**array1)

print("Sin of array = ",np.sin(array1))
print("Logarithm of array = ",np.log(array1))
print("Base-2 logarithm  of array = ",np.log2(array1))
print("Base-10 logarithm of array = ",np.log10(array1))
print("Exponential of array = ",np.exp(array1))

print("Addition of Two arrays {array1} and {array2} = ",array1+array2)